# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 21:45
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=b'ID')),
                ('boolean_1', models.BooleanField(db_column=b'boolean1', default=True, help_text=b'This is the first boolean', verbose_name=b'Boolean_1')),
                ('boolean_2', models.BooleanField(db_column=b'boolean2', default=False, help_text=b'This is the second boolean', verbose_name=b'Boolean_2')),
                ('char_1', models.CharField(blank=True, db_column=b'char1', help_text=b'This is the first char', max_length=10, null=True, verbose_name=b'Char_1')),
                ('char_2', models.CharField(db_column=b'char2', help_text=b'This is the second char', max_length=20, verbose_name=b'Char_2')),
                ('char_3', models.CharField(db_column=b'char3', help_text=b'This is the third char', max_length=30, null=True, verbose_name=b'Char_3')),
                ('char_4', models.CharField(blank=True, db_column=b'char4', help_text=b'This is the fourth char', max_length=250, verbose_name=b'Char_4')),
            ],
        ),
    ]
