# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangopy2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'DB table custom', 'verbose_name_plural': 'DB tables custom'},
        ),
        migrations.AlterField(
            model_name='test',
            name='char_1',
            field=models.CharField(blank=True, db_column='char1', default='char1', help_text='This is the first char', max_length=10, null=True, verbose_name='Char_1'),
        ),
        migrations.AlterField(
            model_name='test',
            name='char_2',
            field=models.CharField(db_column='char2', default='char2', help_text='This is the second char', max_length=20, verbose_name='Char_2'),
        ),
        migrations.AlterField(
            model_name='test',
            name='char_3',
            field=models.CharField(db_column='char3', default='char3', help_text='This is the third char', max_length=30, null=True, verbose_name='Char_3'),
        ),
        migrations.AlterField(
            model_name='test',
            name='char_4',
            field=models.CharField(blank=True, db_column='char4', default='char4', help_text='This is the fourth char', max_length=250, verbose_name='Char_4'),
        ),
        migrations.AlterModelTable(
            name='test',
            table='db_table_custom',
        ),
    ]
